/* automatically generated by rust-bindgen */

pub const FIDO_ERR_SUCCESS: u32 = 0;
pub const FIDO_ERR_INVALID_COMMAND: u32 = 1;
pub const FIDO_ERR_INVALID_PARAMETER: u32 = 2;
pub const FIDO_ERR_INVALID_LENGTH: u32 = 3;
pub const FIDO_ERR_INVALID_SEQ: u32 = 4;
pub const FIDO_ERR_TIMEOUT: u32 = 5;
pub const FIDO_ERR_CHANNEL_BUSY: u32 = 6;
pub const FIDO_ERR_LOCK_REQUIRED: u32 = 10;
pub const FIDO_ERR_INVALID_CHANNEL: u32 = 11;
pub const FIDO_ERR_CBOR_UNEXPECTED_TYPE: u32 = 17;
pub const FIDO_ERR_INVALID_CBOR: u32 = 18;
pub const FIDO_ERR_MISSING_PARAMETER: u32 = 20;
pub const FIDO_ERR_LIMIT_EXCEEDED: u32 = 21;
pub const FIDO_ERR_UNSUPPORTED_EXTENSION: u32 = 22;
pub const FIDO_ERR_CREDENTIAL_EXCLUDED: u32 = 25;
pub const FIDO_ERR_PROCESSING: u32 = 33;
pub const FIDO_ERR_INVALID_CREDENTIAL: u32 = 34;
pub const FIDO_ERR_USER_ACTION_PENDING: u32 = 35;
pub const FIDO_ERR_OPERATION_PENDING: u32 = 36;
pub const FIDO_ERR_NO_OPERATIONS: u32 = 37;
pub const FIDO_ERR_UNSUPPORTED_ALGORITHM: u32 = 38;
pub const FIDO_ERR_OPERATION_DENIED: u32 = 39;
pub const FIDO_ERR_KEY_STORE_FULL: u32 = 40;
pub const FIDO_ERR_NOT_BUSY: u32 = 41;
pub const FIDO_ERR_NO_OPERATION_PENDING: u32 = 42;
pub const FIDO_ERR_UNSUPPORTED_OPTION: u32 = 43;
pub const FIDO_ERR_INVALID_OPTION: u32 = 44;
pub const FIDO_ERR_KEEPALIVE_CANCEL: u32 = 45;
pub const FIDO_ERR_NO_CREDENTIALS: u32 = 46;
pub const FIDO_ERR_USER_ACTION_TIMEOUT: u32 = 47;
pub const FIDO_ERR_NOT_ALLOWED: u32 = 48;
pub const FIDO_ERR_PIN_INVALID: u32 = 49;
pub const FIDO_ERR_PIN_BLOCKED: u32 = 50;
pub const FIDO_ERR_PIN_AUTH_INVALID: u32 = 51;
pub const FIDO_ERR_PIN_AUTH_BLOCKED: u32 = 52;
pub const FIDO_ERR_PIN_NOT_SET: u32 = 53;
pub const FIDO_ERR_PIN_REQUIRED: u32 = 54;
pub const FIDO_ERR_PIN_POLICY_VIOLATION: u32 = 55;
pub const FIDO_ERR_PIN_TOKEN_EXPIRED: u32 = 56;
pub const FIDO_ERR_REQUEST_TOO_LARGE: u32 = 57;
pub const FIDO_ERR_ACTION_TIMEOUT: u32 = 58;
pub const FIDO_ERR_UP_REQUIRED: u32 = 59;
pub const FIDO_ERR_ERR_OTHER: u32 = 127;
pub const FIDO_ERR_SPEC_LAST: u32 = 223;
pub const FIDO_OK: u32 = 0;
pub const FIDO_ERR_TX: i32 = -1;
pub const FIDO_ERR_RX: i32 = -2;
pub const FIDO_ERR_RX_NOT_CBOR: i32 = -3;
pub const FIDO_ERR_RX_INVALID_CBOR: i32 = -4;
pub const FIDO_ERR_INVALID_PARAM: i32 = -5;
pub const FIDO_ERR_INVALID_SIG: i32 = -6;
pub const FIDO_ERR_INVALID_ARGUMENT: i32 = -7;
pub const FIDO_ERR_USER_PRESENCE_REQUIRED: i32 = -8;
pub const FIDO_ERR_INTERNAL: i32 = -9;
pub const CTAP_AUTHDATA_USER_PRESENT: u32 = 1;
pub const CTAP_AUTHDATA_USER_VERIFIED: u32 = 4;
pub const CTAP_AUTHDATA_ATT_CRED: u32 = 64;
pub const CTAP_AUTHDATA_EXT_DATA: u32 = 128;
pub const CTAP_CMD_PING: u32 = 1;
pub const CTAP_CMD_MSG: u32 = 3;
pub const CTAP_CMD_LOCK: u32 = 4;
pub const CTAP_CMD_INIT: u32 = 6;
pub const CTAP_CMD_WINK: u32 = 8;
pub const CTAP_CMD_CBOR: u32 = 16;
pub const CTAP_KEEPALIVE: u32 = 59;
pub const CTAP_FRAME_INIT: u32 = 128;
pub const CTAP_CBOR_MAKECRED: u32 = 1;
pub const CTAP_CBOR_ASSERT: u32 = 2;
pub const CTAP_CBOR_GETINFO: u32 = 4;
pub const CTAP_CBOR_CLIENT_PIN: u32 = 6;
pub const CTAP_CBOR_RESET: u32 = 7;
pub const CTAP_CBOR_NEXT_ASSERT: u32 = 8;
pub const CTAP_CBOR_CRED_MGMT_PRE: u32 = 65;
pub const U2F_CMD_REGISTER: u32 = 1;
pub const U2F_CMD_AUTH: u32 = 2;
pub const U2F_AUTH_SIGN: u32 = 3;
pub const U2F_AUTH_CHECK: u32 = 7;
pub const CTAP_CID_BROADCAST: u32 = 4294967295;
pub const CTAP_RPT_SIZE: u32 = 64;
pub const FIDO_RANDOM_DEV: &'static [u8; 13usize] = b"/dev/urandom\0";
pub const FIDO_CAP_WINK: u32 = 1;
pub const FIDO_CAP_CBOR: u32 = 4;
pub const FIDO_CAP_NMSG: u32 = 8;
pub const COSE_ES256: i32 = -7;
pub const COSE_EDDSA: i32 = -8;
pub const COSE_RS256: i32 = -257;
pub const COSE_KTY_OKP: u32 = 1;
pub const COSE_KTY_EC2: u32 = 2;
pub const COSE_KTY_RSA: u32 = 3;
pub const COSE_P256: u32 = 1;
pub const COSE_ED25519: u32 = 6;
pub const FIDO_EXT_HMAC_SECRET: u32 = 1;
pub const FIDO_DEBUG: u32 = 1;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint64_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct evp_pkey_st {
    _unused: [u8; 0],
}
pub type EVP_PKEY = evp_pkey_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rsa_st {
    _unused: [u8; 0],
}
pub type RSA = rsa_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ec_key_st {
    _unused: [u8; 0],
}
pub type EC_KEY = ec_key_st;
pub type fido_dev_io_open_t = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void,
>;
pub type fido_dev_io_close_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
pub type fido_dev_io_read_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *mut ::std::os::raw::c_uchar,
        arg3: usize,
        arg4: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type fido_dev_io_write_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fido_dev_io {
    pub open: fido_dev_io_open_t,
    pub close: fido_dev_io_close_t,
    pub read: fido_dev_io_read_t,
    pub write: fido_dev_io_write_t,
}
#[test]
fn bindgen_test_layout_fido_dev_io() {
    assert_eq!(
        ::std::mem::size_of::<fido_dev_io>(),
        32usize,
        concat!("Size of: ", stringify!(fido_dev_io))
    );
    assert_eq!(
        ::std::mem::align_of::<fido_dev_io>(),
        8usize,
        concat!("Alignment of ", stringify!(fido_dev_io))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<fido_dev_io>())).open as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(fido_dev_io),
            "::",
            stringify!(open)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<fido_dev_io>())).close as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(fido_dev_io),
            "::",
            stringify!(close)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<fido_dev_io>())).read as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(fido_dev_io),
            "::",
            stringify!(read)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<fido_dev_io>())).write as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(fido_dev_io),
            "::",
            stringify!(write)
        )
    );
}
pub type fido_dev_io_t = fido_dev_io;
pub const fido_opt_t_FIDO_OPT_OMIT: fido_opt_t = 0;
pub const fido_opt_t_FIDO_OPT_FALSE: fido_opt_t = 1;
pub const fido_opt_t_FIDO_OPT_TRUE: fido_opt_t = 2;
pub type fido_opt_t = u32;
extern "C" {
    pub fn fido_strerr(arg1: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fido_assert {
    _unused: [u8; 0],
}
pub type fido_assert_t = fido_assert;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fido_cbor_info {
    _unused: [u8; 0],
}
pub type fido_cbor_info_t = fido_cbor_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fido_cred {
    _unused: [u8; 0],
}
pub type fido_cred_t = fido_cred;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fido_dev {
    _unused: [u8; 0],
}
pub type fido_dev_t = fido_dev;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fido_dev_info {
    _unused: [u8; 0],
}
pub type fido_dev_info_t = fido_dev_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct es256_pk {
    _unused: [u8; 0],
}
pub type es256_pk_t = es256_pk;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rs256_pk {
    _unused: [u8; 0],
}
pub type rs256_pk_t = rs256_pk;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct eddsa_pk {
    _unused: [u8; 0],
}
pub type eddsa_pk_t = eddsa_pk;
extern "C" {
    pub fn fido_assert_new() -> *mut fido_assert_t;
}
extern "C" {
    pub fn fido_cred_new() -> *mut fido_cred_t;
}
extern "C" {
    pub fn fido_dev_new() -> *mut fido_dev_t;
}
extern "C" {
    pub fn fido_dev_info_new(arg1: usize) -> *mut fido_dev_info_t;
}
extern "C" {
    pub fn fido_cbor_info_new() -> *mut fido_cbor_info_t;
}
extern "C" {
    pub fn fido_assert_free(arg1: *mut *mut fido_assert_t);
}
extern "C" {
    pub fn fido_cbor_info_free(arg1: *mut *mut fido_cbor_info_t);
}
extern "C" {
    pub fn fido_cred_free(arg1: *mut *mut fido_cred_t);
}
extern "C" {
    pub fn fido_dev_force_fido2(arg1: *mut fido_dev_t);
}
extern "C" {
    pub fn fido_dev_force_u2f(arg1: *mut fido_dev_t);
}
extern "C" {
    pub fn fido_dev_free(arg1: *mut *mut fido_dev_t);
}
extern "C" {
    pub fn fido_dev_info_free(arg1: *mut *mut fido_dev_info_t, arg2: usize);
}
extern "C" {
    pub fn fido_init(arg1: ::std::os::raw::c_int);
}
extern "C" {
    pub fn fido_assert_authdata_ptr(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_assert_clientdata_hash_ptr(
        arg1: *const fido_assert_t,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_assert_hmac_secret_ptr(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_assert_id_ptr(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_assert_sig_ptr(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_assert_user_id_ptr(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cbor_info_extensions_ptr(
        arg1: *const fido_cbor_info_t,
    ) -> *mut *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cbor_info_options_name_ptr(
        arg1: *const fido_cbor_info_t,
    ) -> *mut *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cbor_info_versions_ptr(
        arg1: *const fido_cbor_info_t,
    ) -> *mut *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cbor_info_options_value_ptr(arg1: *const fido_cbor_info_t) -> *const bool;
}
extern "C" {
    pub fn fido_assert_rp_id(arg1: *const fido_assert_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_assert_user_display_name(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_assert_user_icon(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_assert_user_name(
        arg1: *const fido_assert_t,
        arg2: usize,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cred_display_name(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cred_fmt(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cred_rp_id(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cred_rp_name(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_cred_user_name(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_dev_info_manufacturer_string(
        arg1: *const fido_dev_info_t,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_dev_info_path(arg1: *const fido_dev_info_t) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_dev_info_product_string(
        arg1: *const fido_dev_info_t,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn fido_dev_info_ptr(arg1: *const fido_dev_info_t, arg2: usize) -> *const fido_dev_info_t;
}
extern "C" {
    pub fn fido_cbor_info_protocols_ptr(arg1: *const fido_cbor_info_t) -> *const u8;
}
extern "C" {
    pub fn fido_cbor_info_aaguid_ptr(
        arg1: *const fido_cbor_info_t,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cred_authdata_ptr(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cred_clientdata_hash_ptr(
        arg1: *const fido_cred_t,
    ) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cred_id_ptr(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cred_user_id_ptr(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cred_pubkey_ptr(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cred_sig_ptr(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_cred_x5c_ptr(arg1: *const fido_cred_t) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn fido_assert_allow_cred(
        arg1: *mut fido_assert_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_authdata(
        arg1: *mut fido_assert_t,
        arg2: usize,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_clientdata_hash(
        arg1: *mut fido_assert_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_count(arg1: *mut fido_assert_t, arg2: usize) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_extensions(
        arg1: *mut fido_assert_t,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_hmac_salt(
        arg1: *mut fido_assert_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_options(
        arg1: *mut fido_assert_t,
        arg2: bool,
        arg3: bool,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_rp(
        arg1: *mut fido_assert_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_up(arg1: *mut fido_assert_t, arg2: fido_opt_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_uv(arg1: *mut fido_assert_t, arg2: fido_opt_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_set_sig(
        arg1: *mut fido_assert_t,
        arg2: usize,
        arg3: *const ::std::os::raw::c_uchar,
        arg4: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_verify(
        arg1: *const fido_assert_t,
        arg2: usize,
        arg3: ::std::os::raw::c_int,
        arg4: *const ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_exclude(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_authdata(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_clientdata_hash(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_extensions(
        arg1: *mut fido_cred_t,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_fmt(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_options(
        arg1: *mut fido_cred_t,
        arg2: bool,
        arg3: bool,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_rk(arg1: *mut fido_cred_t, arg2: fido_opt_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_rp(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_sig(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_type(
        arg1: *mut fido_cred_t,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_uv(arg1: *mut fido_cred_t, arg2: fido_opt_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_type(arg1: *const fido_cred_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_user(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
        arg4: *const ::std::os::raw::c_char,
        arg5: *const ::std::os::raw::c_char,
        arg6: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_set_x509(
        arg1: *mut fido_cred_t,
        arg2: *const ::std::os::raw::c_uchar,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_cred_verify(arg1: *const fido_cred_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_close(arg1: *mut fido_dev_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_get_assert(
        arg1: *mut fido_dev_t,
        arg2: *mut fido_assert_t,
        arg3: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_get_cbor_info(
        arg1: *mut fido_dev_t,
        arg2: *mut fido_cbor_info_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_get_retry_count(
        arg1: *mut fido_dev_t,
        arg2: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_info_manifest(
        arg1: *mut fido_dev_info_t,
        arg2: usize,
        arg3: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_make_cred(
        arg1: *mut fido_dev_t,
        arg2: *mut fido_cred_t,
        arg3: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_open(
        arg1: *mut fido_dev_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_reset(arg1: *mut fido_dev_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_set_io_functions(
        arg1: *mut fido_dev_t,
        arg2: *const fido_dev_io_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_dev_set_pin(
        arg1: *mut fido_dev_t,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fido_assert_authdata_len(arg1: *const fido_assert_t, arg2: usize) -> usize;
}
extern "C" {
    pub fn fido_assert_clientdata_hash_len(arg1: *const fido_assert_t) -> usize;
}
extern "C" {
    pub fn fido_assert_count(arg1: *const fido_assert_t) -> usize;
}
extern "C" {
    pub fn fido_assert_hmac_secret_len(arg1: *const fido_assert_t, arg2: usize) -> usize;
}
extern "C" {
    pub fn fido_assert_id_len(arg1: *const fido_assert_t, arg2: usize) -> usize;
}
extern "C" {
    pub fn fido_assert_sig_len(arg1: *const fido_assert_t, arg2: usize) -> usize;
}
extern "C" {
    pub fn fido_assert_user_id_len(arg1: *const fido_assert_t, arg2: usize) -> usize;
}
extern "C" {
    pub fn fido_cbor_info_aaguid_len(arg1: *const fido_cbor_info_t) -> usize;
}
extern "C" {
    pub fn fido_cbor_info_extensions_len(arg1: *const fido_cbor_info_t) -> usize;
}
extern "C" {
    pub fn fido_cbor_info_options_len(arg1: *const fido_cbor_info_t) -> usize;
}
extern "C" {
    pub fn fido_cbor_info_protocols_len(arg1: *const fido_cbor_info_t) -> usize;
}
extern "C" {
    pub fn fido_cbor_info_versions_len(arg1: *const fido_cbor_info_t) -> usize;
}
extern "C" {
    pub fn fido_cred_authdata_len(arg1: *const fido_cred_t) -> usize;
}
extern "C" {
    pub fn fido_cred_clientdata_hash_len(arg1: *const fido_cred_t) -> usize;
}
extern "C" {
    pub fn fido_cred_id_len(arg1: *const fido_cred_t) -> usize;
}
extern "C" {
    pub fn fido_cred_user_id_len(arg1: *const fido_cred_t) -> usize;
}
extern "C" {
    pub fn fido_cred_pubkey_len(arg1: *const fido_cred_t) -> usize;
}
extern "C" {
    pub fn fido_cred_sig_len(arg1: *const fido_cred_t) -> usize;
}
extern "C" {
    pub fn fido_cred_x5c_len(arg1: *const fido_cred_t) -> usize;
}
extern "C" {
    pub fn fido_assert_flags(arg1: *const fido_assert_t, arg2: usize) -> u8;
}
extern "C" {
    pub fn fido_cred_flags(arg1: *const fido_cred_t) -> u8;
}
extern "C" {
    pub fn fido_dev_protocol(arg1: *const fido_dev_t) -> u8;
}
extern "C" {
    pub fn fido_dev_major(arg1: *const fido_dev_t) -> u8;
}
extern "C" {
    pub fn fido_dev_minor(arg1: *const fido_dev_t) -> u8;
}
extern "C" {
    pub fn fido_dev_build(arg1: *const fido_dev_t) -> u8;
}
extern "C" {
    pub fn fido_dev_flags(arg1: *const fido_dev_t) -> u8;
}
extern "C" {
    pub fn fido_dev_info_vendor(arg1: *const fido_dev_info_t) -> i16;
}
extern "C" {
    pub fn fido_dev_info_product(arg1: *const fido_dev_info_t) -> i16;
}
extern "C" {
    pub fn fido_cbor_info_maxmsgsiz(arg1: *const fido_cbor_info_t) -> u64;
}
extern "C" {
    pub fn fido_dev_is_fido2(arg1: *const fido_dev_t) -> bool;
}
extern "C" {
    pub fn es256_pk_new() -> *mut es256_pk_t;
}
extern "C" {
    pub fn es256_pk_free(arg1: *mut *mut es256_pk_t);
}
extern "C" {
    pub fn es256_pk_to_EVP_PKEY(arg1: *const es256_pk_t) -> *mut EVP_PKEY;
}
extern "C" {
    pub fn es256_pk_from_EC_KEY(
        arg1: *mut es256_pk_t,
        arg2: *const EC_KEY,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn es256_pk_from_ptr(
        arg1: *mut es256_pk_t,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rs256_pk_new() -> *mut rs256_pk_t;
}
extern "C" {
    pub fn rs256_pk_free(arg1: *mut *mut rs256_pk_t);
}
extern "C" {
    pub fn rs256_pk_to_EVP_PKEY(arg1: *const rs256_pk_t) -> *mut EVP_PKEY;
}
extern "C" {
    pub fn rs256_pk_from_RSA(arg1: *mut rs256_pk_t, arg2: *const RSA) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rs256_pk_from_ptr(
        arg1: *mut rs256_pk_t,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn eddsa_pk_new() -> *mut eddsa_pk_t;
}
extern "C" {
    pub fn eddsa_pk_free(arg1: *mut *mut eddsa_pk_t);
}
extern "C" {
    pub fn eddsa_pk_to_EVP_PKEY(arg1: *const eddsa_pk_t) -> *mut EVP_PKEY;
}
extern "C" {
    pub fn eddsa_pk_from_EVP_PKEY(
        arg1: *mut eddsa_pk_t,
        arg2: *const EVP_PKEY,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn eddsa_pk_from_ptr(
        arg1: *mut eddsa_pk_t,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
    ) -> ::std::os::raw::c_int;
}
