[package]
name = "libfido2"
version = "0.1.0"
authors = ["PvdBerg1998 <PvdBerg1998@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bitflags = "^1.1.0"
libfido2_sys = { path = "..\\libfido2_sys" }
