[package]
name = "libfido2"
version = "0.1.0"
authors = ["PvdBerg1998 <PvdBerg1998@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "libfido2"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
libfido2_sys = { path = "..\\libfido2_sys" }
